version: '2.1'
services:

    stuffer:
        build:
            context: ./services/stuffer
            dockerfile: Dockerfile
        networks:
            - production
        ports:
            - ${HUMBLE_PORT}:8080
        volumes:
            - ./data/stuffer:/var/lib/stuffer/data
            - ./stuffer-config.json:/var/lib/stuffer/stuffer-config.json
        environment:
            NODE_ENV: production

networks:
    production:
