version: '2.1'
services:

    stuffer:
        build:
            context: ./services/stuffer
            dockerfile: Dockerfile.dev
        networks:
            - development
        ports:
            - ${HUMBLE_PORT:-8080}:8080
        environment:
            NODE_ENV: ${NODE_ENV:-development}
            LOG_LEVEL: ${LOG_LEVEL:-info}
        volumes:
            - ./services/stuffer/ssr:/usr/src/app/ssr
            - ./stuffer-config.json:/var/lib/stuffer/stuffer-config.json
            - ./data/stuffer:/var/lib/stuffer/data
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start" ]
    
networks:
    development:
